server:
  port: 8888
# 配置MySQL数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/intelligenttrafficdb?useSSL=false&&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml